language: node_js
node_js:
  - "lts/*"
  - "node"
cache: yarn
before_install:
  - nvm install --lts
  - nvm use --lts
before_script:
  - yarn build:node
  - yarn build:test
  - yarn link
  - nvm use $TRAVIS_NODE_VERSION
jobs:
  include:
    - stage: "Heimdall"
      name: "Test"
      script: yarn test

    - stage: "Integration Tests"
      name: "ember-cli"
      script: ./scripts/ember-cli-test.sh
